font:
  size: 11
  # TODO fall back font?
  bold:
    family: "CaskaydiaMono Nerd Font"
    style: "Bold"

  bold_italic:
    family: "CaskaydiaMono Nerd Font"
    style: "Bold Italic"

  italic:
    family: "CaskaydiaMono Nerd Font"
    style: "Italic"

  normal:
    family: "CaskaydiaMono Nerd Font"
    style: "Regular"

window:
  padding:
    x: 15
    y: 10

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000

draw_bold_text_with_bright_colors: true

schemes:
  Catppuccin-Mocha: &Catppuccin-Mocha
    primary:
        background: "#1E1E2E" # base
        foreground: "#CDD6F4" # text
        # Bright and dim foreground colors
        dim_foreground: "#CDD6F4" # text
        bright_foreground: "#CDD6F4" # text

    # Cursor colors
    cursor:
        text: "#1E1E2E" # base
        cursor: "#F5E0DC" # rosewater
    vi_mode_cursor:
        text: "#1E1E2E" # base
        cursor: "#B4BEFE" # lavender

    # Search colors
    search:
        matches:
            foreground: "#1E1E2E" # base
            background: "#A6ADC8" # subtext0
        focused_match:
            foreground: "#1E1E2E" # base
            background: "#A6E3A1" # green
        footer_bar:
            foreground: "#1E1E2E" # base
            background: "#A6ADC8" # subtext0

    # Keyboard regex hints
    hints:
        start:
            foreground: "#1E1E2E" # base
            background: "#F9E2AF" # yellow
        end:
            foreground: "#1E1E2E" # base
            background: "#A6ADC8" # subtext0

    # Selection colors
    selection:
        text: "#1E1E2E" # base
        background: "#F5E0DC" # rosewater

    # Normal colors
    normal:
        black: "#45475A" # surface1
        red: "#F38BA8" # red
        green: "#A6E3A1" # green
        yellow: "#F9E2AF" # yellow
        blue: "#89B4FA" # blue
        magenta: "#F5C2E7" # pink
        cyan: "#94E2D5" # teal
        white: "#BAC2DE" # subtext1

    # Bright colors
    bright:
        black: "#585B70" # surface2
        red: "#F38BA8" # red
        green: "#A6E3A1" # green
        yellow: "#F9E2AF" # yellow
        blue: "#89B4FA" # blue
        magenta: "#F5C2E7" # pink
        cyan: "#94E2D5" # teal
        white: "#A6ADC8" # subtext0

    # Dim colors
    dim:
        black: "#45475A" # surface1
        red: "#F38BA8" # red
        green: "#A6E3A1" # green
        yellow: "#F9E2AF" # yellow
        blue: "#89B4FA" # blue
        magenta: "#F5C2E7" # pink
        cyan: "#94E2D5" # teal
        white: "#BAC2DE" # subtext1

    indexed_colors:
        - { index: 16, color: "#FAB387" }
        - { index: 17, color: "#F5E0DC" }

  TomorrowNight: &TomorrowNight
     # Default colors
    primary:
      background: '#1d1f21'
      foreground: '#c5c8c6'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#1d1f21'
      cursor: '#ffffff'

    # Normal colors
    normal:
      black:   '#1d1f21'
      red:     '#cc6666'
      green:   '#b5bd68'
      yellow:  '#e6c547'
      blue:    '#81a2be'
      magenta: '#b294bb'
      cyan:    '#70c0ba'
      white:   '#373b41'

    # Bright colors
    bright:
      black:   '#666666'
      red:     '#ff3334'
      green:   '#9ec400'
      yellow:  '#f0c674'
      blue:    '#81a2be'
      magenta: '#b77ee0'
      cyan:    '#54ced6'
      white:   '#282a2e'

  DoomOne: &DoomOne
    primary:
      background: '#282c34'
      foreground: '#bbc2cf'
    cursor:
      text: CellBackground
      cursor: '#528bff'
    selection:
      text: CellForeground
      background: '#3e4451'
    normal:
      black:   '#1c1f24'
      red:     '#ff6c6b'
      green:   '#98be65'
      yellow:  '#da8548'
      blue:    '#51afef'
      magenta: '#c678dd'
      cyan:    '#5699af'
      white:   '#abb2bf'
    bright:
      black:   '#5b6268'
      red:     '#da8548'
      green:   '#4db5bd'
      yellow:  '#ecbe7b'
      blue:    '#3071db'
      magenta: '#a9a1e1'
      cyan:    '#46d9ff'
      white:   '#dfdfdf'


# Set color scheme, currently available:
#  - "Catppuccin-Mocha"
#  - "TomorrowNight"
#  - "DoomOne"

colors: *Catppuccin-Mocha

key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: Insert,    mods: Shift,         action: PasteSelection              }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Equals,    mods: Control,       action: IncreaseFontSize            }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: F11,       mods: None,          action: ToggleFullscreen            }
  - { key: Paste,     mods: None,          action: Paste                       }
  - { key: Copy,      mods: None,          action: Copy                        }
  - { key: L,         mods: Control,       action: ClearLogNotice              }
  - { key: L,         mods: Control,       chars: "\x0c"                       }
  - { key: PageUp,    mods: None,          action: ScrollPageUp,   mode: ~Alt  }
  - { key: PageDown,  mods: None,          action: ScrollPageDown, mode: ~Alt  }
  - { key: Home,      mods: Shift,         action: ScrollToTop,    mode: ~Alt  }
  - { key: End,       mods: Shift,         action: ScrollToBottom, mode: ~Alt  }
