# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# other stuff
font_size 11.0
font_family      Maple Mono
bold_font        Maple Mono Bold
italic_font      Maple Mono Italic
bold_italic_font Maple Mono BoldItalic

# window padding
window_padding_width 5