# other stuff
font_size 11.0
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font BoldItalic

# window padding
window_padding_width 5

linux_display_server x11