env = QT_QPA_PLATFORM, wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1
env = QT_QPA_PLATFORMTHEME, qt6ct
env = _JAVA_AWT_WM_NONREPARENTING=1
env = WLR_NO_HARDWARE_CURSORS,1
env = HYPRCURSOR_THEME,Catppuccin-Mocha-Dark
env = HYPRCURSOR_SIZE,24