
# Windowrules
windowrulev2 = float, class: (steam)
windowrulev2 = float, class: (.*), title: (Open .*)
windowrulev2 = float, class: (Alacritty)
windowrulev2 = float, silent, class: (thunar)
windowrulev2 = float, class: (nwg-look)
windowrulev2 = float, class: (seahorse)
windowrulev2 = float, class: (mpv)
windowrulev2 = float, class: (org.gnome.Loupe)
windowrulev2 = float, class: (1Password)
windowrulev2 = float, class: (Postman)
windowrulev2 = float, class: (pavucontrol)
windowrulev2 = float, class: (GitKraken)
windowrulev2 = float, class: (blueman-manager)

# idle inhibit
windowrulev2 = idleinhibit fullscreen, class: ^(.*)$

# transparency
windowrulev2 = opacity 0.8 0.8, class: ^(.*)$
#windowrulev2 = opacity 1, class: (firefox), title: ^(.*(Netflix|Crunchyroll|YouTube|Twitch).*)$
#windowrulev2 = opacity 1, class: ^(firefox)$