
# Execs
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-clip-persist --clipboard both
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprctl setcursor Catppuccin-Mocha-Light-Cursors 24
exec-once = eww --config "$HOME/.config/eww/dashboard" open dashboard
exec-once = waybar
#exec-once = bash ~/.config/hypr/scripts/idle.sh
exec-once = bash ~/.config/rofi/scripts/wallpaper.sh
#exec-once = bash ~/.config/hypr/scripts/fixmemclock.sh

# """auto start"""
exec-once = openrgb --startminimized --profile "kabuki"
exec-once = coolercontrol
exec-once = corectrl
exec-once = 1password --silent