[Setting]
overwrite_assets        = 0
spotify_path            = /home/michael/.local/share/spotify-launcher/install/usr/share/spotify
# spotify_path            = /opt/spotify/
prefs_path              = /home/michael/.config/spotify/prefs
current_theme           = catppuccin
color_scheme            = mocha
inject_css              = 1
inject_theme_js         = 1
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 1

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
experimental_features = 1
extensions            = 
custom_apps           = 
sidebar_config        = 1
home_config           = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.20.1210.g2a8a8a57
with    = Dev
