#################
### AUTOSTART ###
#################

exec-once = filen-desktop &
exec-once = sleep 5 && waypaper --restore &
exec-once = swww-daemon &
exec-once = /usr/bin/dunst &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
exec-once = waybar &
exec-once = hypridle &
exec-once = bitwarden-desktop &