#################
### AUTOSTART ###
#################

exec-once = swaync &
exec-once = swww-daemon &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = waybar &
exec-once = wal -R -n &