#####################, title:^(Steam)$
### WINDOW RULES ####
#####################

# Ref https://wiki.hyprland.org/Configuring/Window-Rules/

windowrulev2 = suppressevent maximize, class:.*

# workspace rules
windowrulev2 = workspace 1, class:(kitty)
windowrulev2 = workspace 2, class:(firefox)
windowrulev2 = workspace 3, class:(code)
windowrulev2 = workspace 4, class:(vesktop)
windowrulev2 = workspace 5, class:(Spotify)
windowrulev2 = workspace 6 silent, class:^([Ss]team)$, title:^([Ss]team)$

# floating, 1280x720, centered
# 1password
windowrulev2 = float, class:(1Password)
windowrulev2 = size 1280 720, class:(1Password)
windowrulev2 = center, class:(1Password)
# nwg-look
windowrulev2 = float, class:(nwg-look)
windowrulev2 = size 1280 720, class:(nwg-look)
windowrulev2 = center, class:(nwg-look)
# steam
windowrulev2 = float, class:(steam)
windowrulev2 = size 1280 720, class:(steam), title:^(Steam)$
windowrulev2 = center, class:(steam), title:^(Steam)$
# heroic
windowrulev2 = float, class:(heroic)
windowrulev2 = size 1280 720, class:(heroic)
windowrulev2 = center, class:(heroic)
# mpv // video player
windowrulev2 = float, class:(mpv)
windowrulev2 = size 1280 720, class:(mpv)
windowrulev2 = center, class:(mpv)
# eog // image viewer
windowrulev2 = float, class:(eog)
windowrulev2 = size 1280 720, class:(eog)
windowrulev2 = center, class:(eog)
# sleepy launcher // zzz game
windowrulev2 = float, class:(moe.launcher.sleepy-launcher)
windowrulev2 = size 1280 720, class:(moe.launcher.sleepy-launcher)
windowrulev2 = center, class:(moe.launcher.sleepy-launcher)
# pulseaudio control
windowrulev2 = float, class:(org.pulseaudio.pavucontrol)
windowrulev2 = size 1280 720, class:(org.pulseaudio.pavucontrol)
windowrulev2 = center, class:(org.pulseaudio.pavucontrol)
# nautilus
windowrulev2 = float, class:(org.gnome.Nautilus)
windowrulev2 = size 1280 720, class:(org.gnome.Nautilus)
windowrulev2 = center, class:(org.gnome.Nautilus)
# cooler control
windowrulev2 = float, class:(org.coolercontrol.CoolerControl)
windowrulev2 = size 1280 720, class:(org.coolercontrol.CoolerControl)
windowrulev2 = center, class:(org.coolercontrol.CoolerControl)
# openrgb
windowrulev2 = float, class:(openrgb)
windowrulev2 = size 1280 720, class:(openrgb)
windowrulev2 = center, class:(openrgb)

# make all windows transparent, except for fullscreen windows
windowrulev2 = opacity 0.9, class:^(.*)$
windowrulev2 = opacity 1.0, fullscreen:1
windowrulev2 = opacity 1.0, class:^(firefox)$

# disable animations, initial focus, max size and blur for xwaylandvideobridge
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$

layerrule = blur, rofi # enable blur for rofi layer