#!/bin/bash

## Get data
STATUS="$(playerctl -p spotify status)"

## Get status
get_status() {
	while true; do
		if [ "$(playerctl -p spotify status)" = "Playing" ]; then
			echo "󰏤"
		else
			echo "󰐊"
		fi
		sleep 1
	done
}

## Get song
get_song() {
	while true; do
	  song="$(playerctl -p spotify metadata xesam:title)"
		if [[ -z "$song" ]]; then
			echo "Offline"
		else
			echo "$song"
		fi
		sleep 1
	done		
}

## Get artist
get_artist() {
	while true; do
		artist="$(playerctl -p spotify metadata xesam:artist)"
		if [[ -z "$artist" ]]; then
			echo ""
		else
			echo "$artist"
		fi
		sleep 1
	done	
}


## Get cover
get_cover() {
	while true; do
	  if [ "$STATUS" = "Playing" ] || [ "$STATUS" == "Paused" ];then
	    echo "$(playerctl -p spotify metadata mpris:artUrl)"
	  else
	    echo "img/music"
	  fi
		sleep 1
	done
}

## Toggle status
toggle() {
  playerctl -p spotify play-pause
}

## Next
next() {
  playerctl -p spotify next
}

## Previous
previous() {
  playerctl -p spotify previous
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	toggle
elif [[ "$1" == "--next" ]]; then
	next
elif [[ "$1" == "--prev" ]]; then
	previous
fi
