# variables
export DOTFILES="${HOME}/.dotfiles"
export ZSH_DIR="${DOTFILES}/zsh"
export ANTIDOTE_HOME="${ZSH_DIR}/antidote"
export ZSH_LOCAL="$ZSH_DIR/local"
mkdir -p $ZSH_LOCAL
export ZSH_COMPDUMP="$ZSH_LOCAL/zcompdump-${SHORT_HOST:-${HOST}}-${ZSH_VERSION}"
export HISTFILE="$ZSH_LOCAL/history"
export _Z_DATA="${ZSH_LOCAL}/z"
export STARSHIP_CONFIG="${ZSH_DIR}/starship.toml"

# antidote
zstyle ':antidote:bundle' use-friendly-names 'yes'
if [[ ! $ZSH_LOCAL/plugins.zsh -nt $ZSH_DIR/zsh.plugins ]]; then
  [[ -e $ANTIDOTE_HOME ]] \
    || git clone --depth=1 https://github.com/mattmc3/antidote.git $ANTIDOTE_HOME
  [[ -e $ZSH_DIR/zsh.plugins ]] || touch $ZSH_DIR/zsh.plugins
  (
    source $ANTIDOTE_HOME/antidote.zsh
    antidote bundle <$ZSH_DIR/zsh.plugins >$ZSH_LOCAL/plugins.zsh
  )
fi

source $ZSH_LOCAL/plugins.zsh

# load other stuff
for file in ${ZSH_DIR}/{paths,config,omz}.zsh; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# 1password
source $DOTFILES/ssh/agent-bridge.sh

# starship
eval "$(starship init zsh)"

# fast-syntax-highlighting
FSH_THEME="default"
FSH_CURRENT_THEME=""
if [[ -f "$ZSH_LOCAL/theme.fsh" ]]; then
  read FSH_CURRENT_THEME < "$ZSH_LOCAL/theme.fsh"
fi
if [[ $FSH_CURRENT_THEME != $FSH_THEME ]]; then
  fast-theme $FSH_THEME
  echo $FSH_THEME > "$ZSH_LOCAL/theme.fsh"
  FSH_OVERLAY="$ZSH_DIR/plugin-configs/fast-syntax-highlighting/$FSH_THEME-overlay.ini"
  if [[ -e $FSH_OVERLAY ]]; then
    fast-theme $FSH_OVERLAY
  fi
  unset FSH_OVERLAY
fi
unset FSH_THEME
unset FSH_CURRENT_THEME

unset ZSH_LOCAL
unset ZSH_DIR
export GOPATH="$HOME/go"; export GOROOT="$HOME/.go"; export PATH="$GOPATH/bin:$PATH"; # g-install: do NOT edit, see https://github.com/stefanmaric/g
