# variables
export DOTFILES="${HOME}/.dotfiles"
ZSH_DIR="${DOTFILES}/zsh"
export ANTIDOTE_HOME="${ZSH_DIR}/antidote"
ZSH_LOCAL="$ZSH_DIR/local"
mkdir -p $ZSH_LOCAL
export ZSH_COMPDUMP="$ZSH_LOCAL/zcompdump-${SHORT_HOST:-${HOST}}-${ZSH_VERSION}"
export HISTFILE="$ZSH_LOCAL/history"
export _Z_DATA="${ZSH_LOCAL}/z"

# antidote
zstyle ':antidote:bundle' use-friendly-names 'yes'
if [[ ! $ZSH_LOCAL/plugins.zsh -nt $ZSH_DIR/zsh.plugins ]]; then
  [[ -e $ANTIDOTE_HOME ]] \
    || git clone --depth=1 https://github.com/mattmc3/antidote.git $ANTIDOTE_HOME
  [[ -e $ZSH_DIR/zsh.plugins ]] || touch $ZSH_DIR/zsh.plugins
  (
    source $ANTIDOTE_HOME/antidote.zsh
    antidote bundle <$ZSH_DIR/zsh.plugins >$ZSH_LOCAL/plugins.zsh
  )
fi

source $ZSH_LOCAL/plugins.zsh

# load other stuff
for file in ${ZSH_DIR}/{paths,config}.zsh; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

source $ZSH_DIR/p10k.zsh

# 1password
source ${DOTFILES}/ssh/agent-bridge.sh
